language: go
go:
  - '1.10'
env:
  global:
    - secure: VKL1BYA/XVAdkUpru0N+nCcQoAVh03K01bpHZXuDsAmVv//ttUv7jKrXs6nySIeM4J1qV2m7Fpn3vph/S0fOkf+KG+D25TH6nwczUeA0gD4byxIkDSWfCaChMYAfdTHx/DLNKOAD5nFgYpTdRSVEvrm9hvYb/hfiRQyexXR0QhM+ugBK8G8sg14Ektkb/mN4c+E3qrnfwkgqE6qwHvGdn+4E0gD/axiBSpsF2tGXfLtLdZp3rUJbDkZggCT55OLrMuj+m0fnlgvVWC77pj0k7idoS4aTZCWewpEGWgH8cvtso4xwuxkRyULNrYu8j7dYa1SOBWSi7uXDRGeiYevpIaLuNtfakEwNI/hZwnB5pUv3wQ12dOAI2SrCr9lUPYns6Js3+ep9+JCP07njDGq7qwdzaS9BCMq5HP+xRtHq17JBPO2OzUnjjwAtNUaG3JyFKGKJl6ct2l+XVl6kRlWIvfcMv7V9lqHIKE4L+BgyBmVXy8NIrF7HpaFnDxsyrfRNIPv00lz2JAlrYPz+UaLHbdxVe2Z8W9OTl3LJVzSxaPdEQlR08DIwNDct2cedsWMrvtoo/a4xUJMdOGsAS9YaGfAX1L3U2t9EGY+K5eU9zrfGOTvma0vF2FtDdSPwLod6X4lR7jiqX1mMAk4GwgjY3r3KCReuc2uDiwOOIzBAGFo=
    - secure: Fn6QzViKWkaWNrbEzsybfxm1v2xC8OBhVlHpy9FT/AHqSe1Brm0fpfyzAjlsNnWexjMTbFFrYkGrVKN2cPbJTw9purC4V9kPyC+qOx5cjHEP7Q7naY9zNcfy6IpZAKE2clVCx3NbnrRWwSXv0Ojl4X3idOplF8IrI0rnckosQLEdpdes6JRfw0AJKxN5orw9omX6bnYh1KrAitIHYzaNjvhr3hpilX9zdLpagKKaIa8q1aTwZJb8UDUS/1PfS9StqQoyjrzASaOj6Z9i8fLGn1dRMLJW63k4fND0JNNw/jc+j/XGfZZo/WQMokATr3YZ8SwVrQPus8AyDeB+gsgPMkW/i4jCqy6L+Yf0FKMfuZqJHUbBCEQo6ET77D9IxtZ7aRy9EaTQUJlVMw/DTOmdyjip4SVBgSy879DpWz/YKlYOpZTNM8Hresii2HoxrelCgga3BDn85e4CWnAo2DWsLNm3or2PVIZErTWThC3qVdBlyDloJ2TyjQOD2+eQjMWtrFRCFewNfVLAtOSjxa8RBc7QkHrVoBC4fY0FDUk2yC4lo7iNgWnj0ydMz9qeM4Pxvi6jtsDyC/F2Ejm1Pql5XgdzxCZM7Fmhe2BdGWjKuBUif32+rYrRu2EhocUjogHfEg/72IPy/8HCjawtwNS0vfY4vG73zOIMHjEsfedxuI8=
    - secure: qdwdHiXf1il45JbQ8hNbuYeCPFn25Xj8TMSMq2NyZmt4pRp+D+DeJQr3W7P2TazWQLyKWFRAfUPLqAo4UGF3BC4hoSQ9uv4WVXnoNmmRmr2SaMAX2gaKwi88Ex7zFvnxGBy4rMUaqXMiBxUQ+IxggFXB516h9B1URuWTs8xqzke1Z8DDPZyU0ONLA2GACX6TTaxVL7GmdfRm7jOYSw3L24qNvwjQNG0rKT81CsseJyI4BhytEpZrJKwCCedzg39RMIlyD5d8SmzDQY0gMVRHiakzZKHHSk4R/Zc5oU90tDbc5jJOXMSvsSAp+YmfrdPzQGUBYLs0VcqN8dAQmRKHx66geY7nw025QI9Dl9kl6Mi6PH806TCQpBBUPlJnSJ3Yf6RreBqo16vmorI0/TR74OcYq1ZLWroxTcDv0xhzkIj4YjD06We6nEKIVGGIERV+aJroL8oLYhVGqvIkAidz/7ww18B9hOz/r6AS4GQcJINI2o1LyJRU4NDt3FMknHmnTRZxcP164mOO45P2NBtjVxFxemJc7tUtRR1uJidOx7J0EIMT8UCTknZVBoLisB2YTLEKjwAzyGnteuj28T+yy8uMzFreyhaixkmCzzsrpxSayrAeW3uOK3u2YiU9xm4A2XpaIOs24toWq153cKmvpjhovwMILFeluNmy+tXfQYM=
    - secure: sQPIumlZNRPjyY+OUAhnGV+kxoLeCeMVHKsYBJJM1a3DRUQwWlkjonqZLLh54KyaP+MkQCLacZfQ8lQ40ETMjGlRo9hh3KJ8EMJmjQjg6wZJa1bPBy97nLgzmCaQGCkq+HFUROGZnB+8wFLK35xZSsEfLEyJZFjOTOkxC2/LmrMzkF4b2A/9dg6agCZQLAJD0A5pgwngO3EbS70b84lQo/XL4O8bVsEZ0utDn6Aj9xHEgPjvw3VsI2LZL5qds2Y+175dk33R3TW8wp7esaeQq6DXPym+XWb8XcNEapOSUyxkdwvlwpRB4VcqPwpPmPdCe8qoGH+RERq9l3/0cI3gGQSdzFEz3UkrOdYR8LREzMg2e17dsOhOYAqAPfLgDoJ+QoRrFmfNkvWgAUuhLLwnoA3IwDXnLHbhJ4kKUS304VcKOd8B+w5jhora01kgHlpKJiMQixW+87BAwQFCP9T+TO1vQRjQhqzx314Uws5xargT9eGobpHoO8dTCApdMgf03pGD/T4wF/vUd6STWEYU1XbGdE2N9S1Tmu4F7bHEE8MTv1lyo1Yt+ES5RmjvALN8kfZBWdEtZX7fmvnCA76uYFuztmLYG5OqA6huNaTI2cDZ1gwyITyrscEXRafOey1OW52w2mFQeJcHLWiK8EFZy+eQgM5+Td/5nO70MTzPv4A=
before_deploy:
  - make cross-build
  - make dist
  - make publish
  - mkdir -p public-script && cp script/install.sh public-script/ev-cli
deploy:
  - provider: releases
    skip_cleanup: true
    api_key: "$GITHUB_TOKEN"
    file_glob: true
    file: dist/*.{tar.gz,zip}
    on:
      tags: true
  - provider: s3
    access-key-id: "$AWS_ACCESS_KEY_ID"
    secret-access-key: "$AWS_SECRET_ACCESS_KEY"
    region: "$AWS_REGION"
    bucket: private-dev-tools.wantedly.com
    skip_cleanup: true
    local-dir: dist/publish
    upload-dir: ev-cli
    acl: public_read
    on:
      tags: true
  - provider: s3
    access-key-id: "$AWS_ACCESS_KEY_ID"
    secret-access-key: "$AWS_SECRET_ACCESS_KEY"
    region: "$AWS_REGION"
    bucket: get.wantedlyapp.com
    skip_cleanup: true
    local-dir: public-script
    acl: public_read
    on:
      branch: master
